version: "3.8" # Specify the Docker Compose file format version
services:
  postgres:
    image: postgres:15 # Use the official PostgreSQL image
    container_name: postgres_container
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistent data storage

  app:
    image: pet_places
    build:
      context: ./backend
    container_name: pet_places_app
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable

    depends_on:
      - postgres # Ensure the database starts before the app
    ports:
      - "8080:8080"
    extra_hosts:
      - "postgres:127.0.0.1"
      - "somehost:162.242.195.82"
      - "otherhost:50.31.209.229"

  frontend:
    image: pet_places_frontend
    build:
      context: ./frontend
    container_name: pet_places_frontend
    ports:
      - "5000:80"
    depends_on:
      - app # Ensure the backend starts before the frontend

volumes:
  postgres_data: # Persistent storage for PostgreSQL
  # Naming on github action
