version: "3.8" # Specify the Docker Compose file format version
services:
  postgres:
    image: postgres:15 # Use the official PostgreSQL image
    container_name: postgres_container
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistent data storage

  app:
    image: pet_places
    build:
      context: . # Use the current directory to build the image
    container_name: pet_places_app
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
      # TEST_DATABASE_URL: ${TEST_DATABASE_URL}
    depends_on:
      - postgres # Ensure the database starts before the app
    ports:
      - "8080:8080"

volumes:
  postgres_data:
